#ifndef INSTRUMENTATIONPARAM_H_
#define INSTRUMENTATIONPARAM_H_

typedef enum {
	MODEM,
	DATA_RATE,
	FREQUENCYBAND,
	POWER_INDEX,
	ADR,
	DUTY_CYCLE,
	GATEWAY_COUNT,
	SNR,
	SP_FACTOR,
	BANDWIDTH,
	CODING_RATE,
	RETRANSMISSION_COUNT
} instrumentationParam;

#endif  /* INSTRUMENTATIONPARAM_H_ */
